# This Docker-Compose file is FOR DEVELOPMENT. When you are able to build project yourself.
version: "3.3"

networks:
  opba-net:

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"           # Traefik HTTP
      #- "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
    networks:
      - opba-net

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=open_banking
    ports:
      #HOST:CONTAINER
      - "5432:5432"
    volumes:
      - ./opba-db/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./fintech-examples/fintech-db-schema/src/main/resources/init.sql:/docker-entrypoint-initdb.d/fintech-init.sql
    networks:
      - opba-net

  open-banking-gateway:
    environment:
      - SPRING_LIQUIBASE_PARAMETERS_ADORSYS-SANDBOX-URL=https://obg-bank-dev-xs2a.cloud.adorsys.de
      - SPRING_LIQUIBASE_PARAMETERS_ADORSYS-HBCI-SANDBOX-URL=http://hbci-sandbox:8090/hbci-mock/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/open_banking?currentSchema=banking_protocol
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker
      - PROTOCOL_XS2A_PKCS12_KEYSTORE=/pkcs12/sample-qwac.keystore
      - FACADE_ENCRYPTION_KEYSETPATH=/keysetpath/example-keyset.json
      - FACADE_URLS_EMBEDDED-UI-BASE-URL=http://localhost:14200
      - PROTOCOL_GATEWAY-BASE-URL=http://localhost:18085
    image: ghcr.io/adorsys/open-banking-gateway:latest-develop
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.obg.rule=Host(`obg.obgdeb.com`)"
      - "traefik.http.services.obg.loadbalancer.server.port=8085"
      - "traefik.http.routers.obg.entrypoints=web"
    volumes:
      - ./opba-protocols/xs2a-protocol/src/main/resources/:/pkcs12/
      - ./opba-banking-protocol-facade/src/main/resources/:/keysetpath/
    depends_on:
      - postgres
    networks:
      - opba-net

  fintech-ui:
    environment:
      - APP_TYPE=fintech
      - BACKEND_URL=http://fintech-server:8086
    entrypoint: [ "/entry.sh" ]
    restart: on-failure
    image: ghcr.io/adorsys/fintech-ui:16d7941-develop
    volumes:
       - ./nginx/default.conf.erb:/etc/nginx/conf.d/default.conf.erb:ro
       - ./nginx/entry.sh:/entry.sh:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=opba-net"
      - "traefik.http.routers.ui.rule=Host(`fintech-ui.obgdeb.com`)"
      - "traefik.http.services.ui.loadbalancer.server.port=4200"
      - "traefik.http.routers.ui.entrypoints=web"
    depends_on:
      - fintech-server
    networks:
      - opba-net

  fintech-server:
    environment:
      - TPP_URL=http://open-banking-gateway:8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/open_banking?currentSchema=fintech
      - FINTECH-UI_HOST=http://localhost:24200
    image: ghcr.io/adorsys/fintech-server:latest-develop
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fintech.rule=Host(`fintech-server.obgdeb.com`)"
      - "traefik.http.services.fintech.loadbalancer.server.port=8086"
      - "traefik.http.routers.fintech.entrypoints=web"
    depends_on:
      - postgres
    networks:
      - opba-net

  consent-ui:
    environment:
      - BACKEND_URL=http://open-banking-gateway:8085
      - APP_TYPE=consent
    restart: on-failure
    image: ghcr.io/adorsys/consent-ui:60033fc-develop
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/entry.sh:/entry.sh:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=opba-net"
      - "traefik.http.routers.consent.rule=Host(`consent.obgdeb.com`)"
      - "traefik.http.services.consent.loadbalancer.server.port=4200"
      - "traefik.http.routers.consent.entrypoints=web"
    depends_on:
      - open-banking-gateway
    networks:
      - opba-net

  hbci-sandbox-server:
    restart: on-failure
    image: ghcr.io/adorsys/hbci-sandbox-server:latest-develop
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sandbox.rule=Host(`sandbox.obgdeb.com`)"
      - "traefik.http.routers.sandbox.entrypoints=web"
      - "traefik.http.services.sandbox.loadbalancer.server.port=8090"
    networks:
      - opba-net